let htmlWeek = document.querySelector("#week")
let htmlMonth = document.querySelector("#month")
let htmlYear = document.querySelector("#year")
let htmlTime = document.querySelector("#time")
let htmlAlarm = document.querySelector("#alarm")
let htmloff = document.querySelector("#off")